/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tmEyqERUc4L
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import Image from "next/image"

export function HomePage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[#0C2340] text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <FlagIcon className="h-6 w-6" />
          <span className="sr-only">React Chicago Meetup</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Meetups
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Speakers
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Sponsors
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#0C2340]">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none text-[#CC0000]">
                    React Chicago Meetup
                  </h1>
                  <p className="max-w-[600px] text-[#FFFFFF]">
                    Join us for the latest updates, discussions, and networking in the React community.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#CC0000] px-8 text-sm font-medium text-[#FFFFFF] shadow transition-colors hover:bg-[#CC0000]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Upcoming Meetup
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-[#FFFFFF] bg-[#0C2340] px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#FFFFFF] hover:text-[#0C2340] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Past Meetups
                  </Link>
                </div>
              </div>
              <div className="flex justify-center">
                <Image width={500} height={100} src="/placeholder.svg" alt="Chicago" className="h-[300px] w-[300px]" />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#FFFFFF] text-[#0C2340]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Upcoming Meetup</h2>
                <p className="max-w-[900px] text-[#0C2340] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Join us for our next React Chicago meetup on May 15th, 2023 at 6:30 PM. We'll be discussing the latest
                  trends and innovations in the React ecosystem.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#CC0000] px-8 text-sm font-medium text-[#FFFFFF] shadow transition-colors hover:bg-[#CC0000]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  RSVP Now
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-[#0C2340] bg-[#FFFFFF] px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#0C2340] hover:text-[#FFFFFF] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  View Details
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#0C2340] text-[#FFFFFF]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Speakers</h2>
                <p className="max-w-[900px] text-[#FFFFFF] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Learn from the best in the React community at our upcoming meetup. Check out our featured speakers
                  below.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                <Card className="bg-[#FFFFFF] text-[#0C2340]">
                  <CardHeader>
                    <Image
                      src="/placeholder.svg"
                      width={300}
                      height={300}
                      alt="Speaker"
                      className="rounded-t-lg object-cover"
                      style={{ aspectRatio: "300/300", objectFit: "cover" }}
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">John Doe</h3>
                    <p className="text-sm text-muted-foreground">Senior React Developer</p>
                  </CardContent>
                </Card>
                <Card className="bg-[#FFFFFF] text-[#0C2340]">
                  <CardHeader>
                    <Image
                      src="/placeholder.svg"
                      width={300}
                      height={300}
                      alt="Speaker"
                      className="rounded-t-lg object-cover"
                      style={{ aspectRatio: "300/300", objectFit: "cover" }}
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Jane Smith</h3>
                    <p className="text-sm text-muted-foreground">React Architect</p>
                  </CardContent>
                </Card>
                <Card className="bg-[#FFFFFF] text-[#0C2340]">
                  <CardHeader>
                    <Image
                      src="/placeholder.svg"
                      width={300}
                      height={300}
                      alt="Speaker"
                      className="rounded-t-lg object-cover"
                      style={{ aspectRatio: "300/300", objectFit: "cover" }}
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Michael Johnson</h3>
                    <p className="text-sm text-muted-foreground">React Consultant</p>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#FFFFFF] text-[#0C2340]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Partners</h2>
                <p className="max-w-[900px] text-[#0C2340] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  We&apos;re grateful for the support of our sponsors, who help make the React Chicago meetup possible.
                </p>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-6">
                <Image
                  src="/placeholder.svg"
                  width={140}
                  height={70}
                  alt="Sponsor"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                />
                <Image
                  src="/placeholder.svg"
                  width={140}
                  height={70}
                  alt="Sponsor"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                />
                <Image
                  src="/placeholder.svg"
                  width={140}
                  height={70}
                  alt="Sponsor"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                />
                <Image
                  src="/placeholder.svg"
                  width={140}
                  height={70}
                  alt="Sponsor"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-[#0C2340] text-[#FFFFFF]">
        <p className="text-xs text-[#FFFFFF]">&copy; 2024 React Chicago Meetup. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
